### ISSUE TITLE
Random Mounts (more)

### ISSUE THREAD

**Issue by Kelesti** [goatcorp/suggestions#402] opened 2021-05-01 03:55 UTC
### Description
I have a lot of mounts I like to cycle between, from raids and rare achievements, to ones that just look nice on my character, but I've found out that "Random Favorite" doesn't actually hold enough space.

### More info
I want to be able to whitelist a lot of mounts, and just push a button (even if that button is a macro) and pull from them at random.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by AmenneHolelane** [comment] 2021-05-01 04:05
QOLBar does have a solution for this

**Comment by AmenneHolelane** [comment] 2021-05-01 04:07
duplicate of #280

**Closed** 2021-05-01 04:07 UTC
Labels: duplicate
