### ISSUE TITLE
"center the map on player position" is always toggled off

### ISSUE THREAD

**Issue by Veis11** [goatcorp/suggestions#937] opened 2022-05-21 11:13 UTC
### Plugin Description

Plugin to make it so that "center map on player location" isn't always toggled on by default. it moves the map out of frame every time i open it.

### Request Terms

- [X] I checked if this request wasn't already proposed
- [X] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher)

**Comment by kalilistic** [comment] 2022-05-21 14:05
Thanks for raising a ticket but looks like a duplicate of https://github.com/goatcorp/suggestions/issues/617.

**Closed as completed by kalilistic** 2022-05-21 14:05 UTC
Labels: invalid, discussion requested
