### ISSUE TITLE
WoW Total RP

### ISSUE THREAD

**Issue by kalilistic** [goatcorp/suggestions#92] opened 2021-03-30 23:44 UTC
### Description
A plugin for roleplayers similar to wows "total RP 3" addon". after creating your profile you could then generate a string you can place in the search info that other players could copy or iff possible the plugin could auto read when you open search info and then it would load that players RP profile.

### More info
Is this already implemented by "Expanded Search Info"?
See https://discord.com/channels/581875019861328007/685275026156683280/759141407520063500 for more information.

Original requester: `Lynsis#4220`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Dalamud's [plugin guidelines](https://github.com/goatcorp/FFXIVQuickLauncher#isnt-this-cheating)

**Comment by lmcintyre** [comment] 2021-03-30 23:52
Duplicate of #26

**Closed** 2021-03-31 01:43 UTC
Labels: duplicate
